### ISSUE TITLE
Review / add efs for cspace tmp

### ISSUE THREAD

**Issue by mark-cooper** [dts-hosting/terraform-aws-cspace#17]
Implemented in existing playbook to account for (rare) cases when total size of files in cache exceeds container disk space causing a crash (this is likely a bug in the current version of cspace & may be an underlying nuxeo issue [given old version of nuxeo being used]).

Alternative: increase frequency with which the clear tmp cron job runs (currently once per day).

**Comment by mglyrasis** [comment]
@mark-cooper 

This was implemented in the form of both moving the `/apache/temp` directory to EFS-based storage as well as increasing the cron frequency to every 3 hours.

Also of note: We tested moving `/apache/nuxeo-server/tmp` to EFS, but startup failed because of missing `/apache/nuxeo-server/tmp/schemas` directory. Mark and I talked about potentially preserving the directory at build and then copying it back at runtime, but that seemed like too many moving parts.

The actual solution here should be that CollectionSpace cleans up temporary files when it's done using them, not manually with external jobs.
